name: dxjoke Tectonic Docker

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1 
      - name: Create source directory
        run:  mkdir -p ${{ github.workspace }}/src
      - name: Compile
        run: |
          pwd
          ls -a
          docker run --mount src=$GITHUB_WORKSPACE/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker:latest /bin/sh -c main.tex 
          echo "Ran the docker thing"
      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: main.zip
          path: src/main.pdf
