name: dxjoke Tectonic Docker

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1 
      - name: Create source directory
        run:  mkdir -p ${{ github.workspace }}/src
      - name: Compile
        run: |
          docker run --mount src=$GITHUB_WORKSPACE/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker:latest tectonic /usr/src/tex/main.tex
          echo "Ran the docker thing"
      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: main.zip
          path: src/main.pdf
      # Step 5: Commit and push PDF back to repository
      - name: Commit and push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add src/main.pdf
          git commit -m "Add generated main.pdf"
          git push -u origin @

